name: Frontend CD

on:
  push:
    branches:
      - master
    paths:
      - 'mapmymoments-FE/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd mapmymoments-FE
          npm install

      - name: Build frontend
        run: |
          cd mapmymoments-FE
          npm run build

      - name: Copy build files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" mapmymoments-FE/dist/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/mapmymoments/frontend/